openapi: 3.0.3
info:
  title: Payment Query API
  description: |
    API to query information about a specific payment. The query operation is a server-to-server HTTP POST used by the merchant website to query EBANX for information about a specific payment.
  version: 1.0.0
servers:
  - url: https://sandbox.ebanxpay.com/
    description: Sandbox API Server
  - url: https://api.ebanxpay.com/
    description: Production API Server
paths:
  /ws/query:
    post:
      summary: Payment Query
      description: Queries information about a specific payment using either query string parameters or request body.
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/QueryBodyHashRequest'
                - $ref: '#/components/schemas/QueryBodyMerchantPaymentCodeRequest'
            examples:
              example-1:
                value:
                  hash: "5552f1dd61f85171e67376719896b1559d01c43ab62b1f97"
                  merchant_payment_code: "111122220924400593471283000056"
                  integration_key: "************************P8ZlBQ"
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/QueryBodyHashResponse'
              examples:
                example-1:
                  value:
                    payment:
                      hash: "55e2f1dd61f85171e67376719896b1559d01c43ab62b1f97"
                      country: "mx"
                      merchant_payment_code: "111122220924400593471283000056"
                      order_number: null
                      status: "PE"
                      status_date: null
                      open_date: "2024-09-24 17:07:41"
                      confirm_date: null
                      transfer_date: null
                      amount_br: "185.57"
                      amount_ext: "185.57"
                      amount_iof: "0.00"
                      amount_ext_requested: "185.57"
                      currency_rate: "1.0000"
                      currency_ext: "MXN"
                      due_date: "2024-09-27"
                      instalments: "1"
                      payment_type_code: "oxxopay"
                      voucher_url: "https://print.ebanx.com/print/voucher/execute?hash=55e2f1dd61f85171e67376719896b1559d01c43ab62b1f97"
                      pre_approved: false
                      capture_available: null
                      oxxopay_barcode: "3600000489663011"
                    status: "SUCCESS"
                example-2:
                  value:
                    status: "SUCCESS"
                    payment:
                      hash: "54737a76ffc1e5a520b0ed9062213a810ef41dae990184c7"
                      merchant_payment_code: "1416854121"
                      order_number: null
                      status: "CO"
                      status_date: "2014-11-24 16:35:43"
                      open_date: "2014-11-24 16:35:34"
                      confirm_date: "2014-11-24 16:35:43"
                      transfer_date: null
                      amount_br: "352.50"
                      amount_ext: "150.00"
                      amount_iof: "0.00"
                      currency_rate: "2.3500"
                      currency_ext: "USD"
                      due_date: "2014-12-01"
                      instalments: "1"
                      payment_type_code: "bradesco"
                      pre_approved: false
                      capture_available: null
                      refunds:
                        - id: "9283"
                          merchant_refund_code: null
                          status: "RE"
                          request_date: "2014-11-26 17:56:52"
                          pending_date: null
                          confirm_date: null
                          cancel_date: null
                          paid_date: null
                          amount_ext: "100.00"
                          description: "Order did not arrive"
                          settlement:
                            transfer_date: "2014-12-01"
                            amount: 100
                          refund_status_details:
                            cancellation_reason: "Not Paid: refund payment period has been exceed"
                            cancellation_reason_code: "RSD-01"
                            can_have_settlement: true
                            can_be_cancelled: false
components:
  schemas:
    QueryBodyHashRequest:
      type: object
      title: Pix Payment Request
      description: Request payload to initiate a Pix payment.
      properties:
        integration_key:
          description: Your unique and secret integration key.
          type: string
          maxLength: 100
        hash:
          description: The payment hash (EBANX unique identifier). Required if `merchant_payment_code` is not provided.
          type: string
          minLength: 48
          maxLength: 48
        merchant_payment_code:
          description: The payment hash Merchant Payment Code (unique merchant ID). Required if `hash` is not provided.
          type: string
          minLength: 1
          maxLength: 40
      required:
        - hash
        - integration_key
    QueryBodyMerchantPaymentCodeRequest:
      type: object
      title: Pix Payment Request
      description: Request payload to initiate a Pix payment.
      properties:
        integration_key:
          description: Your unique and secret integration key.
          type: string
          maxLength: 100
        hash:
          description: The payment hash (EBANX unique identifier). Required if `merchant_payment_code` is not provided.
          type: string
          minLength: 48
          maxLength: 48
        merchant_payment_code:
          description: The payment hash Merchant Payment Code (unique merchant ID). Required if `hash` is not provided.
          type: string
          minLength: 1
          maxLength: 40
      required:
        - hash
        - merchant_payment_code
    QueryBodyHashResponse:
      type: object
      description: Successful response with payment information.
      properties:
        status:
          type: string
          description: The status of the request (SUCCESS or ERROR).
          minLength: 5
          maxLength: 7
        payment:
          type: object
          properties:
            hash:
              type: string
              description: The payment hash (Empresa unique identifier).
              minLength: 48
              maxLength: 48
            country:
              type: string
              description: The country of the payment.
              minLength: 2
              maxLength: 2
            merchant_payment_code:
              type: string
              description: The payment hash Merchant Payment Code (unique merchant ID).
              minLength: 1
              maxLength: 40
            order_number:
              type: string
              description: The order number, an optional identifier set by the merchant.
              minLength: 1
              maxLength: 40
            status:
              type: string
              description: |
                The payment status. The following statuses are available:
                
                OP: the customer has not yet filled the payment details on the EBANX Checkout. It can change either to CA (time out) or PE.
                PE: the payment is pending confirmation. It can change either to CA or CO.
                CO: the payment is confirmed (paid).
                CA: the payment is cancelled.
              minLength: 2
              maxLength: 2
              enum:
                - OP
                - PE
                - CO
                - CA
            status_date:
              type: string
              description: The date and time of the last status change.
              pattern: '^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$'
            open_date:
              type: string
              description: The date and time when the payment was created.
              pattern: '^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$'
            confirm_date:
              type: string
              description: The date and time when the payment was confirmed.
              pattern: '^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$'
            transfer_date:
              type: string
              description: The date and time when the payment was settled.
              pattern: '^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$'
            amount_br:
              type: string
              description: The amount in local currency.
            amount_iof:
              type: string
              description: The tax amount in local currency.
            amount_ext:
              type: string
              description: The amount in the original currency.
            currency_rate:
              type: string
              description: The exchange rate used in the payment.
            currency_ext:
              type: string
              description: The original currency code (ISO 4217).
              minLength: 3
              maxLength: 3
            due_date:
              type: string
              description: The expiry date of the payment (not applicable to all payment methods).
              pattern: '^\\d{4}-\\d{2}-\\d{2}$'
            instalments:
              type: string
              description: The number of instalments for the payment.
              default: '1'
            payment_type_code:
              type: string
              description: The code of the payment method.
              enum:
                - amex
                - bancodobrasil
                - banrisul
                - banktransfer
                - boleto
                - bradesco
                - carnet
                - credimas
                - cupon
                - diners
                - discover
                - eft
                - elo
                - hipercard
                - itau
                - mastercard
                - multicaja
                - naranja
                - oxxo
                - pagoefectivo
                - pagosnet
                - rapipago
                - safetypay
                - safetypay-cash
                - safetypay-online
                - sencillito
                - servipag
                - spei
                - visa
                - webpay
            redirect_url:
              type: string
              description: The URL to which the customer should be redirected.
            pre_approved:
              type: boolean
              description: Indicates if the payment was pre-approved by the credit card acquirer.
            capture_available:
              type: boolean
              description: Indicates if the payment is ready to be captured.